version: '3.9'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: Europe/Rome
      POSTGRES_DB: tot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tot"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: tot-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      TZ: Europe/Rome
      PORT: 3000
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/tot?schema=public"

volumes:
  postgres_data:
